name: Web Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    #Download Repo
    steps:
    - uses: actions/checkout@v4
    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

   - name: setup-chromedriver
  # You may pin to the exact commit or the version.
  # uses: nanasess/setup-chromedriver@42cc2998329f041de87dc3cfa33a930eacd57eaa
  uses: nanasess/setup-chromedriver@v2.2.2
  with:
    # The chromedriver version to install
    chromedriver-version: # optional
          

  - name: Setup Gradlew
    run: chmod +X gradlew

  - name: execute test
    run: ./gradlew cucumbar
  

          
